services:
  web:
    build: .
    container_name: swef_site
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
    depends_on:
      - umami

  umami:
    image: ghcr.io/maxime-j/umami-sqlite:latest
    container_name: umami
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=file:/data/umami.db
      - DATABASE_TYPE=sqlite
      - APP_SECRET=${APP_SECRET}
    volumes:
      - ./umami-data:/data
    restart: always

volumes:
  umami-db-data:
